# Generated by Django 4.0.1 on 2022-01-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='titls',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='answer',
            name='dislike',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.IntegerField(),
        ),
    ]
