# Generated by Django 3.2.4 on 2022-01-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='favorite',
            field=models.IntegerField(default=0),
        ),
    ]
