# Generated by Django 4.0.1 on 2022-01-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_titls_question_title_alter_answer_dislike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='view',
            field=models.IntegerField(null=True),
        ),
    ]
