# Generated by Django 3.2.4 on 2022-01-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
