# Generated by Django 3.2.4 on 2022-01-29 17:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220129_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='dislike',
        ),
        migrations.AddField(
            model_name='question',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
