# Generated by Django 4.0.1 on 2022-01-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_answer_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='host',
        ),
    ]
